/********************************************************************
* BLDCWireMapMan_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error BLDCWireMapMan_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableBLDCWireMapMan_Dict();
extern void G__cpp_setup_inheritanceBLDCWireMapMan_Dict();
extern void G__cpp_setup_typetableBLDCWireMapMan_Dict();
extern void G__cpp_setup_memvarBLDCWireMapMan_Dict();
extern void G__cpp_setup_globalBLDCWireMapMan_Dict();
extern void G__cpp_setup_memfuncBLDCWireMapMan_Dict();
extern void G__cpp_setup_funcBLDCWireMapMan_Dict();
extern void G__set_cpp_environmentBLDCWireMapMan_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "BLDCWireMapMan.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__BLDCWireMapMan_DictLN_TClass;
extern G__linked_taginfo G__BLDCWireMapMan_DictLN_TBuffer;
extern G__linked_taginfo G__BLDCWireMapMan_DictLN_TMemberInspector;
extern G__linked_taginfo G__BLDCWireMapMan_DictLN_TObject;
extern G__linked_taginfo G__BLDCWireMapMan_DictLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__BLDCWireMapMan_DictLN_string;
extern G__linked_taginfo G__BLDCWireMapMan_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__BLDCWireMapMan_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BLDCWireMapMan_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__BLDCWireMapMan_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BLDCWireMapMan_DictLN_BLDCWireMap;
extern G__linked_taginfo G__BLDCWireMapMan_DictLN_BLDCWireMapMan;
extern G__linked_taginfo G__BLDCWireMapMan_DictLN_maplEunsignedsPintcOBLDCWireMapcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOBLDCWireMapgRsPgRsPgR;

/* STUB derived class for protected member access */
