/********************************************************************
* CDSFittingParamMan_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error CDSFittingParamMan_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableCDSFittingParamMan_Dict();
extern void G__cpp_setup_inheritanceCDSFittingParamMan_Dict();
extern void G__cpp_setup_typetableCDSFittingParamMan_Dict();
extern void G__cpp_setup_memvarCDSFittingParamMan_Dict();
extern void G__cpp_setup_globalCDSFittingParamMan_Dict();
extern void G__cpp_setup_memfuncCDSFittingParamMan_Dict();
extern void G__cpp_setup_funcCDSFittingParamMan_Dict();
extern void G__set_cpp_environmentCDSFittingParamMan_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "CDSFittingParamMan.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__CDSFittingParamMan_DictLN_TClass;
extern G__linked_taginfo G__CDSFittingParamMan_DictLN_TBuffer;
extern G__linked_taginfo G__CDSFittingParamMan_DictLN_TMemberInspector;
extern G__linked_taginfo G__CDSFittingParamMan_DictLN_TObject;
extern G__linked_taginfo G__CDSFittingParamMan_DictLN_string;
extern G__linked_taginfo G__CDSFittingParamMan_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__CDSFittingParamMan_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CDSFittingParamMan_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__CDSFittingParamMan_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CDSFittingParamMan_DictLN_CDSFittingParamMan;

/* STUB derived class for protected member access */
