/********************************************************************
* ComCrossSectionTable_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ComCrossSectionTable_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableComCrossSectionTable_Dict();
extern void G__cpp_setup_inheritanceComCrossSectionTable_Dict();
extern void G__cpp_setup_typetableComCrossSectionTable_Dict();
extern void G__cpp_setup_memvarComCrossSectionTable_Dict();
extern void G__cpp_setup_globalComCrossSectionTable_Dict();
extern void G__cpp_setup_memfuncComCrossSectionTable_Dict();
extern void G__cpp_setup_funcComCrossSectionTable_Dict();
extern void G__set_cpp_environmentComCrossSectionTable_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "ComCrossSectionTable.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__ComCrossSectionTable_DictLN_TClass;
extern G__linked_taginfo G__ComCrossSectionTable_DictLN_TBuffer;
extern G__linked_taginfo G__ComCrossSectionTable_DictLN_TMemberInspector;
extern G__linked_taginfo G__ComCrossSectionTable_DictLN_TObject;
extern G__linked_taginfo G__ComCrossSectionTable_DictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__ComCrossSectionTable_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__ComCrossSectionTable_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ComCrossSectionTable_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__ComCrossSectionTable_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ComCrossSectionTable_DictLN_CrossSection;
extern G__linked_taginfo G__ComCrossSectionTable_DictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__ComCrossSectionTable_DictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ComCrossSectionTable_DictLN_CrossSectionTable;
extern G__linked_taginfo G__ComCrossSectionTable_DictLN_vectorlECrossSectioncOallocatorlECrossSectiongRsPgR;
extern G__linked_taginfo G__ComCrossSectionTable_DictLN_reverse_iteratorlEvectorlECrossSectioncOallocatorlECrossSectiongRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
