/********************************************************************
* HistInfo_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error HistInfo_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableHistInfo_Dict();
extern void G__cpp_setup_inheritanceHistInfo_Dict();
extern void G__cpp_setup_typetableHistInfo_Dict();
extern void G__cpp_setup_memvarHistInfo_Dict();
extern void G__cpp_setup_globalHistInfo_Dict();
extern void G__cpp_setup_memfuncHistInfo_Dict();
extern void G__cpp_setup_funcHistInfo_Dict();
extern void G__set_cpp_environmentHistInfo_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "HistInfo.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__HistInfo_DictLN_TClass;
extern G__linked_taginfo G__HistInfo_DictLN_TBuffer;
extern G__linked_taginfo G__HistInfo_DictLN_TMemberInspector;
extern G__linked_taginfo G__HistInfo_DictLN_TObject;
extern G__linked_taginfo G__HistInfo_DictLN_TString;
extern G__linked_taginfo G__HistInfo_DictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__HistInfo_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__HistInfo_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__HistInfo_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__HistInfo_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__HistInfo_DictLN_HistInfo;
extern G__linked_taginfo G__HistInfo_DictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__HistInfo_DictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__HistInfo_DictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR;
extern G__linked_taginfo G__HistInfo_DictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
