/********************************************************************
* SlewingMapMan_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error SlewingMapMan_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableSlewingMapMan_Dict();
extern void G__cpp_setup_inheritanceSlewingMapMan_Dict();
extern void G__cpp_setup_typetableSlewingMapMan_Dict();
extern void G__cpp_setup_memvarSlewingMapMan_Dict();
extern void G__cpp_setup_globalSlewingMapMan_Dict();
extern void G__cpp_setup_memfuncSlewingMapMan_Dict();
extern void G__cpp_setup_funcSlewingMapMan_Dict();
extern void G__set_cpp_environmentSlewingMapMan_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "SlewingMapMan.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__SlewingMapMan_DictLN_TClass;
extern G__linked_taginfo G__SlewingMapMan_DictLN_TBuffer;
extern G__linked_taginfo G__SlewingMapMan_DictLN_TMemberInspector;
extern G__linked_taginfo G__SlewingMapMan_DictLN_TObject;
extern G__linked_taginfo G__SlewingMapMan_DictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__SlewingMapMan_DictLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__SlewingMapMan_DictLN_string;
extern G__linked_taginfo G__SlewingMapMan_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__SlewingMapMan_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SlewingMapMan_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__SlewingMapMan_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SlewingMapMan_DictLN_SlewingMap;
extern G__linked_taginfo G__SlewingMapMan_DictLN_maplEunsignedsPintcOSlewingMapcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOSlewingMapgRsPgRsPgR;
extern G__linked_taginfo G__SlewingMapMan_DictLN_SlewingMapMan;
extern G__linked_taginfo G__SlewingMapMan_DictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__SlewingMapMan_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
