/********************************************************************
* TemplateFitter_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TemplateFitter_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTemplateFitter_Dict();
extern void G__cpp_setup_inheritanceTemplateFitter_Dict();
extern void G__cpp_setup_typetableTemplateFitter_Dict();
extern void G__cpp_setup_memvarTemplateFitter_Dict();
extern void G__cpp_setup_globalTemplateFitter_Dict();
extern void G__cpp_setup_memfuncTemplateFitter_Dict();
extern void G__cpp_setup_funcTemplateFitter_Dict();
extern void G__set_cpp_environmentTemplateFitter_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TemplateFitter.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TemplateFitter_DictLN_TClass;
extern G__linked_taginfo G__TemplateFitter_DictLN_TBuffer;
extern G__linked_taginfo G__TemplateFitter_DictLN_TMemberInspector;
extern G__linked_taginfo G__TemplateFitter_DictLN_TObject;
extern G__linked_taginfo G__TemplateFitter_DictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__TemplateFitter_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TemplateFitter_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TemplateFitter_DictLN_TObjArray;
extern G__linked_taginfo G__TemplateFitter_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TemplateFitter_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TemplateFitter_DictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TemplateFitter_DictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TemplateFitter_DictLN_TH1;
extern G__linked_taginfo G__TemplateFitter_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TemplateFitter_DictLN_TFractionFitter;
extern G__linked_taginfo G__TemplateFitter_DictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__TemplateFitter_DictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TemplateFitter_DictLN_TemplateFitter;
extern G__linked_taginfo G__TemplateFitter_DictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__TemplateFitter_DictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TemplateFitter_DictLN_dequelEboolcOallocatorlEboolgRsPgR;

/* STUB derived class for protected member access */
