/********************************************************************
* UshiwakaTableMan_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error UshiwakaTableMan_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableUshiwakaTableMan_Dict();
extern void G__cpp_setup_inheritanceUshiwakaTableMan_Dict();
extern void G__cpp_setup_typetableUshiwakaTableMan_Dict();
extern void G__cpp_setup_memvarUshiwakaTableMan_Dict();
extern void G__cpp_setup_globalUshiwakaTableMan_Dict();
extern void G__cpp_setup_memfuncUshiwakaTableMan_Dict();
extern void G__cpp_setup_funcUshiwakaTableMan_Dict();
extern void G__set_cpp_environmentUshiwakaTableMan_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "UshiwakaTableMan.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__UshiwakaTableMan_DictLN_TClass;
extern G__linked_taginfo G__UshiwakaTableMan_DictLN_TBuffer;
extern G__linked_taginfo G__UshiwakaTableMan_DictLN_TMemberInspector;
extern G__linked_taginfo G__UshiwakaTableMan_DictLN_TObject;
extern G__linked_taginfo G__UshiwakaTableMan_DictLN_string;
extern G__linked_taginfo G__UshiwakaTableMan_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__UshiwakaTableMan_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__UshiwakaTableMan_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__UshiwakaTableMan_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__UshiwakaTableMan_DictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__UshiwakaTableMan_DictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__UshiwakaTableMan_DictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__UshiwakaTableMan_DictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__UshiwakaTableMan_DictLN_UshiwakaTable;
extern G__linked_taginfo G__UshiwakaTableMan_DictLN_UshiwakaTableMan;
extern G__linked_taginfo G__UshiwakaTableMan_DictLN_maplEunsignedsPlongcOUshiwakaTablecOlesslEunsignedsPlonggRcOallocatorlEpairlEconstsPunsignedsPlongcOUshiwakaTablegRsPgRsPgR;

/* STUB derived class for protected member access */
