/********************************************************************
* XTMapMan_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error XTMapMan_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableXTMapMan_Dict();
extern void G__cpp_setup_inheritanceXTMapMan_Dict();
extern void G__cpp_setup_typetableXTMapMan_Dict();
extern void G__cpp_setup_memvarXTMapMan_Dict();
extern void G__cpp_setup_globalXTMapMan_Dict();
extern void G__cpp_setup_memfuncXTMapMan_Dict();
extern void G__cpp_setup_funcXTMapMan_Dict();
extern void G__set_cpp_environmentXTMapMan_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "XTMapMan.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__XTMapMan_DictLN_TClass;
extern G__linked_taginfo G__XTMapMan_DictLN_TBuffer;
extern G__linked_taginfo G__XTMapMan_DictLN_TMemberInspector;
extern G__linked_taginfo G__XTMapMan_DictLN_TObject;
extern G__linked_taginfo G__XTMapMan_DictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__XTMapMan_DictLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__XTMapMan_DictLN_string;
extern G__linked_taginfo G__XTMapMan_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__XTMapMan_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__XTMapMan_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__XTMapMan_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__XTMapMan_DictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__XTMapMan_DictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__XTMapMan_DictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__XTMapMan_DictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__XTMapMan_DictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__XTMapMan_DictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__XTMapMan_DictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__XTMapMan_DictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__XTMapMan_DictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__XTMapMan_DictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__XTMapMan_DictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__XTMapMan_DictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__XTMapMan_DictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__XTMapMan_DictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__XTMapMan_DictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__XTMapMan_DictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__XTMapMan_DictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__XTMapMan_DictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__XTMapMan_DictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__XTMapMan_DictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__XTMapMan_DictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__XTMapMan_DictLN_maplEunsignedsPintcOGeomMapcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOGeomMapgRsPgRsPgR;
extern G__linked_taginfo G__XTMapMan_DictLN_BLDCWireMapMan;
extern G__linked_taginfo G__XTMapMan_DictLN_maplEunsignedsPintcOBLDCWireMapcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOBLDCWireMapgRsPgRsPgR;
extern G__linked_taginfo G__XTMapMan_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__XTMapMan_DictLN_XTMap;
extern G__linked_taginfo G__XTMapMan_DictLN_XTMapMan;
extern G__linked_taginfo G__XTMapMan_DictLN_maplEunsignedsPintcOTGraphcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOTGraphgRsPgRsPgR;
extern G__linked_taginfo G__XTMapMan_DictLN_maplEunsignedsPintcOXTMapcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOXTMapgRsPgRsPgR;
extern G__linked_taginfo G__XTMapMan_DictLN_maplEunsignedsPintcOTH1FcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOTH1FgRsPgRsPgR;

/* STUB derived class for protected member access */
