//Hidemitsu Asano
//Apr. 30 ,2017
//macro to draw hit correlation btw 
//layer 1 and 2  (x,x') 
//layer 3 and 4  (y,y')
//layer 5 and 6  (x,x')
//layer 7 and 8  (y,y')
//
//Input: root file generated by src/EventAnalysisBPC.cpp
//Output: 2D histogram

void DrawBPCCorr(const char *filename="../testbpc.root")
{
  gStyle->SetOptStat(0);
  TFile *f = new TFile(filename,"READ");
  TH2I *h2corr1_2  = (TH2I*) f->Get("WirePatBPC_1");
  TH2I *h2corr3_4  = (TH2I*) f->Get("WirePatBPC_3");
  TH2I *h2corr5_6  = (TH2I*) f->Get("WirePatBPC_5");
  TH2I *h2corr7_8  = (TH2I*) f->Get("WirePatBPC_7");
  
  TCanvas *c1 = new TCanvas("c1","c1",800,800);
  c1->Divide(2,2);
  c1->cd(1);
  h2corr1_2->GetXaxis()->SetTitle("BPC Layer 1 wire ID");
  h2corr1_2->GetXaxis()->CenterTitle();
  h2corr1_2->GetYaxis()->SetTitle("BPC Layer 2 wire ID");
  h2corr1_2->GetYaxis()->CenterTitle();
  h2corr1_2->SetTitle("BPC Hit correlation (X and X')");
  h2corr1_2->Draw("box");
  TLine *line1 = new TLine(0,0,33,33);
  line1->SetLineColor(kRed);
  line1->Draw();
  
  //TCanvas *c2 = new TCanvas("c2","c2",800,800);
  c1->cd(2);
  h2corr3_4->GetXaxis()->SetTitle("BPC Layer 3 wire ID");
  h2corr3_4->GetXaxis()->CenterTitle();
  h2corr3_4->GetYaxis()->SetTitle("BPC Layer 4 wire ID");
  h2corr3_4->GetYaxis()->CenterTitle();
  h2corr3_4->SetTitle("BPC Hit correlation (Y and Y')");
  h2corr3_4->Draw("box");
  TLine *line2 = new TLine(0,0,33,33);
  line2->SetLineColor(kRed);
  line2->Draw();
  
  //TCanvas *c3 = new TCanvas("c3","c3",800,800);
  c1->cd(3);
  h2corr5_6->GetXaxis()->SetTitle("BPC Layer 5 wire ID");
  h2corr5_6->GetXaxis()->CenterTitle();
  h2corr5_6->GetYaxis()->SetTitle("BPC Layer 6 wire ID");
  h2corr5_6->GetYaxis()->CenterTitle();
  h2corr5_6->SetTitle("BPC Hit correlation (X and X')");
  h2corr5_6->Draw("box");
  TLine *line3 = new TLine(0,0,33,33);
  line3->SetLineColor(kRed);
  line3->Draw();
  
  //TCanvas *c4 = new TCanvas("c4","c4",800,800);
  c1->cd(4);
  h2corr7_8->GetXaxis()->SetTitle("BPC Layer 7 wire ID");
  h2corr7_8->GetXaxis()->CenterTitle();
  h2corr7_8->GetYaxis()->SetTitle("BPC Layer 8 wire ID");
  h2corr7_8->GetYaxis()->CenterTitle();
  h2corr7_8->SetTitle("BPC Hit correlation (Y and Y')");
  h2corr7_8->Draw("box");
  TLine *line4 = new TLine(0,0,33,33);
  line4->SetLineColor(kRed);
  line4->Draw();
  
}
