/********************************************************************
* tmp/DetectorList_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error tmp/DetectorList_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableDetectorList_Dict();
extern void G__cpp_setup_inheritanceDetectorList_Dict();
extern void G__cpp_setup_typetableDetectorList_Dict();
extern void G__cpp_setup_memvarDetectorList_Dict();
extern void G__cpp_setup_globalDetectorList_Dict();
extern void G__cpp_setup_memfuncDetectorList_Dict();
extern void G__cpp_setup_funcDetectorList_Dict();
extern void G__set_cpp_environmentDetectorList_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/had/hiasano/ana/k18ana/src/DetectorList.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__DetectorList_DictLN_TClass;
extern G__linked_taginfo G__DetectorList_DictLN_TBuffer;
extern G__linked_taginfo G__DetectorList_DictLN_TMemberInspector;
extern G__linked_taginfo G__DetectorList_DictLN_TObject;
extern G__linked_taginfo G__DetectorList_DictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__DetectorList_DictLN_string;
extern G__linked_taginfo G__DetectorList_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__DetectorList_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DetectorList_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__DetectorList_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DetectorList_DictLN_DetectorList;
extern G__linked_taginfo G__DetectorList_DictLN_DetectorListcLcLgCounterType;
extern G__linked_taginfo G__DetectorList_DictLN_DetectorListcLcLgStringType;
extern G__linked_taginfo G__DetectorList_DictLN_DetectorListcLcLgNumberType;
extern G__linked_taginfo G__DetectorList_DictLN_maplEstringcOunsignedsPintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOunsignedsPintgRsPgRsPgR;
extern G__linked_taginfo G__DetectorList_DictLN_maplEunsignedsPintcOstringcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOstringgRsPgRsPgR;
extern G__linked_taginfo G__DetectorList_DictLN_maplEunsignedsPintcOintcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__DetectorList_DictLN_maplEunsignedsPintcOboolcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOboolgRsPgRsPgR;

/* STUB derived class for protected member access */
