/********************************************************************
* tmp/GainMapMan_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error tmp/GainMapMan_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableGainMapMan_Dict();
extern void G__cpp_setup_inheritanceGainMapMan_Dict();
extern void G__cpp_setup_typetableGainMapMan_Dict();
extern void G__cpp_setup_memvarGainMapMan_Dict();
extern void G__cpp_setup_globalGainMapMan_Dict();
extern void G__cpp_setup_memfuncGainMapMan_Dict();
extern void G__cpp_setup_funcGainMapMan_Dict();
extern void G__set_cpp_environmentGainMapMan_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/had/hiasano/ana/k18ana/src/GainMapMan.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__GainMapMan_DictLN_TClass;
extern G__linked_taginfo G__GainMapMan_DictLN_TBuffer;
extern G__linked_taginfo G__GainMapMan_DictLN_TMemberInspector;
extern G__linked_taginfo G__GainMapMan_DictLN_TObject;
extern G__linked_taginfo G__GainMapMan_DictLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__GainMapMan_DictLN_string;
extern G__linked_taginfo G__GainMapMan_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__GainMapMan_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GainMapMan_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__GainMapMan_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GainMapMan_DictLN_GainMap;
extern G__linked_taginfo G__GainMapMan_DictLN_GainMapMan;
extern G__linked_taginfo G__GainMapMan_DictLN_maplEunsignedsPintcOGainMapcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOGainMapgRsPgRsPgR;

/* STUB derived class for protected member access */
