/********************************************************************
* tmp/CDCWireMapMan_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error tmp/CDCWireMapMan_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableCDCWireMapMan_Dict();
extern void G__cpp_setup_inheritanceCDCWireMapMan_Dict();
extern void G__cpp_setup_typetableCDCWireMapMan_Dict();
extern void G__cpp_setup_memvarCDCWireMapMan_Dict();
extern void G__cpp_setup_globalCDCWireMapMan_Dict();
extern void G__cpp_setup_memfuncCDCWireMapMan_Dict();
extern void G__cpp_setup_funcCDCWireMapMan_Dict();
extern void G__set_cpp_environmentCDCWireMapMan_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/had/tyamaga/private/k18ana/src/CDCWireMapMan.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__CDCWireMapMan_DictLN_TClass;
extern G__linked_taginfo G__CDCWireMapMan_DictLN_TBuffer;
extern G__linked_taginfo G__CDCWireMapMan_DictLN_TMemberInspector;
extern G__linked_taginfo G__CDCWireMapMan_DictLN_TObject;
extern G__linked_taginfo G__CDCWireMapMan_DictLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__CDCWireMapMan_DictLN_string;
extern G__linked_taginfo G__CDCWireMapMan_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__CDCWireMapMan_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CDCWireMapMan_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__CDCWireMapMan_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CDCWireMapMan_DictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__CDCWireMapMan_DictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__CDCWireMapMan_DictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__CDCWireMapMan_DictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__CDCWireMapMan_DictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__CDCWireMapMan_DictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__CDCWireMapMan_DictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__CDCWireMapMan_DictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__CDCWireMapMan_DictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__CDCWireMapMan_DictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__CDCWireMapMan_DictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__CDCWireMapMan_DictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__CDCWireMapMan_DictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__CDCWireMapMan_DictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__CDCWireMapMan_DictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__CDCWireMapMan_DictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__CDCWireMapMan_DictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__CDCWireMapMan_DictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__CDCWireMapMan_DictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__CDCWireMapMan_DictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__CDCWireMapMan_DictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__CDCWireMapMan_DictLN_TVector3;
extern G__linked_taginfo G__CDCWireMapMan_DictLN_CDCWireMap;
extern G__linked_taginfo G__CDCWireMapMan_DictLN_RCDCWireMap;
extern G__linked_taginfo G__CDCWireMapMan_DictLN_CDCWireMapMan;
extern G__linked_taginfo G__CDCWireMapMan_DictLN_maplEunsignedsPintcOCDCWireMapcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOCDCWireMapgRsPgRsPgR;
extern G__linked_taginfo G__CDCWireMapMan_DictLN_maplEunsignedsPintcORCDCWireMapcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcORCDCWireMapgRsPgRsPgR;

/* STUB derived class for protected member access */
