/********************************************************************
* tmp/GeomMapMan_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error tmp/GeomMapMan_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableGeomMapMan_Dict();
extern void G__cpp_setup_inheritanceGeomMapMan_Dict();
extern void G__cpp_setup_typetableGeomMapMan_Dict();
extern void G__cpp_setup_memvarGeomMapMan_Dict();
extern void G__cpp_setup_globalGeomMapMan_Dict();
extern void G__cpp_setup_memfuncGeomMapMan_Dict();
extern void G__cpp_setup_funcGeomMapMan_Dict();
extern void G__set_cpp_environmentGeomMapMan_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/had/tyamaga/private/k18ana/src/GeomMapMan.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__GeomMapMan_DictLN_TClass;
extern G__linked_taginfo G__GeomMapMan_DictLN_TBuffer;
extern G__linked_taginfo G__GeomMapMan_DictLN_TMemberInspector;
extern G__linked_taginfo G__GeomMapMan_DictLN_TObject;
extern G__linked_taginfo G__GeomMapMan_DictLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__GeomMapMan_DictLN_string;
extern G__linked_taginfo G__GeomMapMan_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__GeomMapMan_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GeomMapMan_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__GeomMapMan_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GeomMapMan_DictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__GeomMapMan_DictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__GeomMapMan_DictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__GeomMapMan_DictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__GeomMapMan_DictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__GeomMapMan_DictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__GeomMapMan_DictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__GeomMapMan_DictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__GeomMapMan_DictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__GeomMapMan_DictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__GeomMapMan_DictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__GeomMapMan_DictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__GeomMapMan_DictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__GeomMapMan_DictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__GeomMapMan_DictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__GeomMapMan_DictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__GeomMapMan_DictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__GeomMapMan_DictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__GeomMapMan_DictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__GeomMapMan_DictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__GeomMapMan_DictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__GeomMapMan_DictLN_TVector3;
extern G__linked_taginfo G__GeomMapMan_DictLN_TPolyLine;
extern G__linked_taginfo G__GeomMapMan_DictLN_GeomMap;
extern G__linked_taginfo G__GeomMapMan_DictLN_GeomMapMan;
extern G__linked_taginfo G__GeomMapMan_DictLN_maplEunsignedsPintcOGeomMapcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOGeomMapgRsPgRsPgR;

/* STUB derived class for protected member access */
