/********************************************************************
* tmp/GlobalVariables_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error tmp/GlobalVariables_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableGlobalVariables_Dict();
extern void G__cpp_setup_inheritanceGlobalVariables_Dict();
extern void G__cpp_setup_typetableGlobalVariables_Dict();
extern void G__cpp_setup_memvarGlobalVariables_Dict();
extern void G__cpp_setup_globalGlobalVariables_Dict();
extern void G__cpp_setup_memfuncGlobalVariables_Dict();
extern void G__cpp_setup_funcGlobalVariables_Dict();
extern void G__set_cpp_environmentGlobalVariables_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/had/tyamaga/private/k18ana/src/GlobalVariables.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__GlobalVariables_DictLN_TClass;
extern G__linked_taginfo G__GlobalVariables_DictLN_TBuffer;
extern G__linked_taginfo G__GlobalVariables_DictLN_TMemberInspector;
extern G__linked_taginfo G__GlobalVariables_DictLN_TObject;
extern G__linked_taginfo G__GlobalVariables_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__GlobalVariables_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GlobalVariables_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__GlobalVariables_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GlobalVariables_DictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__GlobalVariables_DictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__GlobalVariables_DictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__GlobalVariables_DictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__GlobalVariables_DictLN_gDataType;
extern G__linked_taginfo G__GlobalVariables_DictLN_gCounterID;
extern G__linked_taginfo G__GlobalVariables_DictLN_gTriggerPattern;
extern G__linked_taginfo G__GlobalVariables_DictLN_GlobalVariables;

/* STUB derived class for protected member access */
