/********************************************************************
* tmp/TransferMatrixMan_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error tmp/TransferMatrixMan_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTransferMatrixMan_Dict();
extern void G__cpp_setup_inheritanceTransferMatrixMan_Dict();
extern void G__cpp_setup_typetableTransferMatrixMan_Dict();
extern void G__cpp_setup_memvarTransferMatrixMan_Dict();
extern void G__cpp_setup_globalTransferMatrixMan_Dict();
extern void G__cpp_setup_memfuncTransferMatrixMan_Dict();
extern void G__cpp_setup_funcTransferMatrixMan_Dict();
extern void G__set_cpp_environmentTransferMatrixMan_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/had/tyamaga/private/k18ana/src/TransferMatrixMan.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TransferMatrixMan_DictLN_TClass;
extern G__linked_taginfo G__TransferMatrixMan_DictLN_TBuffer;
extern G__linked_taginfo G__TransferMatrixMan_DictLN_TMemberInspector;
extern G__linked_taginfo G__TransferMatrixMan_DictLN_TObject;
extern G__linked_taginfo G__TransferMatrixMan_DictLN_string;
extern G__linked_taginfo G__TransferMatrixMan_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TransferMatrixMan_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TransferMatrixMan_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TransferMatrixMan_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TransferMatrixMan_DictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TransferMatrixMan_DictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TransferMatrixMan_DictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TransferMatrixMan_DictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TransferMatrixMan_DictLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__TransferMatrixMan_DictLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__TransferMatrixMan_DictLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__TransferMatrixMan_DictLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__TransferMatrixMan_DictLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__TransferMatrixMan_DictLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__TransferMatrixMan_DictLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__TransferMatrixMan_DictLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__TransferMatrixMan_DictLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__TransferMatrixMan_DictLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__TransferMatrixMan_DictLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__TransferMatrixMan_DictLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__TransferMatrixMan_DictLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__TransferMatrixMan_DictLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__TransferMatrixMan_DictLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__TransferMatrixMan_DictLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__TransferMatrixMan_DictLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__TransferMatrixMan_DictLN_TransferMatrixMan;

/* STUB derived class for protected member access */
